//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonDeviceLogger.DB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertType
    {
        public int AlertTypeId { get; set; }
        public string AlertType1 { get; set; }
        public string MsgSubject { get; set; }
        public string MsgTitle { get; set; }
        public string MsgBody { get; set; }
        public string DemoMessage1 { get; set; }
        public string DemoMessage2 { get; set; }
        public string DemoMessage3 { get; set; }
        public string DemoMessage4 { get; set; }
        public string Comments { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
