//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HorizonDeviceLogger.DB.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceLogs2
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ReceivedDateTime { get; set; }
        public Nullable<decimal> VRN { get; set; }
        public Nullable<decimal> VYN { get; set; }
        public Nullable<decimal> VBN { get; set; }
        public Nullable<decimal> IR { get; set; }
        public Nullable<decimal> IY { get; set; }
        public Nullable<decimal> IB { get; set; }
        public Nullable<decimal> W_R { get; set; }
        public Nullable<decimal> W_Y { get; set; }
        public Nullable<decimal> W_B { get; set; }
        public Nullable<decimal> VA_R { get; set; }
        public Nullable<decimal> VA_Y { get; set; }
        public Nullable<decimal> VA_B { get; set; }
        public Nullable<decimal> VAR_R { get; set; }
        public Nullable<decimal> VAR_Y { get; set; }
        public Nullable<decimal> VAR_B { get; set; }
        public Nullable<decimal> RY { get; set; }
        public Nullable<decimal> YB { get; set; }
        public Nullable<decimal> BR { get; set; }
        public Nullable<decimal> F { get; set; }
        public Nullable<decimal> KWH { get; set; }
        public Nullable<decimal> KVAH { get; set; }
        public Nullable<decimal> PFR { get; set; }
        public Nullable<decimal> PFY { get; set; }
        public Nullable<decimal> PFB { get; set; }
        public Nullable<decimal> PA1 { get; set; }
        public Nullable<decimal> PA2 { get; set; }
        public Nullable<decimal> PA3 { get; set; }
        public Nullable<decimal> VAVG { get; set; }
        public Nullable<decimal> VSM { get; set; }
        public Nullable<decimal> IAVG { get; set; }
        public Nullable<decimal> ISM { get; set; }
        public Nullable<decimal> W_AV { get; set; }
        public Nullable<decimal> W_SM { get; set; }
        public Nullable<decimal> VAAVG { get; set; }
        public Nullable<decimal> VASM { get; set; }
        public Nullable<decimal> PFAV { get; set; }
        public Nullable<decimal> PFSM { get; set; }
        public Nullable<decimal> PAAV { get; set; }
        public Nullable<decimal> PASM { get; set; }
        public string deviceID { get; set; }
        public Nullable<decimal> AI1 { get; set; }
        public Nullable<decimal> AI2 { get; set; }
        public Nullable<decimal> AI3 { get; set; }
        public Nullable<decimal> AI4 { get; set; }
        public Nullable<decimal> AI5 { get; set; }
        public Nullable<decimal> AI6 { get; set; }
        public Nullable<decimal> AI7 { get; set; }
        public Nullable<decimal> AI8 { get; set; }
        public Nullable<decimal> DI1 { get; set; }
        public Nullable<decimal> DI2 { get; set; }
        public Nullable<decimal> DI3 { get; set; }
        public Nullable<decimal> DI4 { get; set; }
        public Nullable<decimal> DI5 { get; set; }
        public Nullable<decimal> DI6 { get; set; }
        public Nullable<decimal> DI7 { get; set; }
        public Nullable<decimal> DI8 { get; set; }
        public Nullable<decimal> DO1 { get; set; }
        public Nullable<decimal> DO2 { get; set; }
        public Nullable<decimal> DO3 { get; set; }
        public Nullable<decimal> DO4 { get; set; }
        public Nullable<decimal> KW { get; set; }
        public Nullable<decimal> KVA { get; set; }
        public Nullable<decimal> KVAR { get; set; }
    }
}
